services:
  app:
    build: .
    image: jhj0517/whisper-webui:latest
    runtime: nvidia
    volumes:
      - /Whisper-WebUI/models
      - /Whisper-WebUI/outputs
    ports:
      - "7860"
    # stdin_open: true
    # tty: true

    entrypoint: ["python", "app.py", "--server_port", "7860", "--server_name", "0.0.0.0",]
    # If you're not using nvidia GPU, Update device to match yours.
    # See more info at : https://docs.docker.com/compose/compose-file/deploy/#driver
    deploy:
      resources:
        reservations:
          devices:
            -
              driver: nvidia
              count: 1
              capabilities:
                - gpu
